export const COOKING_GUIDE_TEXT = "1분 안에 10,000원 이상을 벌어야 합니다. 마우스로 재료를 순서대로 드래그 해서 접시에 올려주세요. 주문대로 만들지 않으면 돈을 잃게 됩니다. 그럼 개점해볼까요?";
export const EXIT = "나가기";
export const START = "시작";
export const OPEN = "개점";
export const RETRY = "다시하기";
export const SUCCESS_TEXT = "성공하셨습니다!";
export const FAILURE_TEXT = "실패하셨습니다!"
export const FISHING_SUCCESS_TEXT = "성공하셨습니다! 그럼 개점해볼까요?";
export const FISHING_GUIDE_TEXT = "1분 안에 요청서에 맞게 마우스로 클릭하여 문어, 참치, 연어, 장어, 새우를 잡아주세요. 실패하면 가게 영업을 할 수 없습니다.";
